// Code generated by go-bindata.
// sources:
// resource/default.zz.lua
// DO NOT EDIT!

package resource

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _resourceDefaultZzLua = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\x50\x4d\x8b\xdb\x30\x10\xbd\xe7\x57\xcc\xcd\x09\x28\x46\xe3\x8f\xc4\xa2\xf4\xb0\x2c\x0b\x7b\x2b\xec\x2e\xf4\x2c\xc7\xb2\x57\x20\xcb\x41\x96\x5b\x42\xc9\x7f\x2f\x33\xb1\xe3\xb4\x3b\x17\xbf\x19\xbd\x79\x7e\xf3\xa2\xae\x9d\x19\xe1\x3b\xfc\xd9\x00\x00\x84\xe1\x37\x37\x28\x05\x64\x52\x40\x2e\x05\x14\x52\x40\x29\x05\x1c\xa4\x80\xa3\x14\x50\x49\x01\x4a\x5e\x05\x2f\xec\xf7\xf0\xfe\xfa\xe3\x27\x3c\xbf\x3e\xbd\x3d\x3d\x7f\xbc\xbc\xc1\xfb\xcb\xc7\x37\x7e\x3a\x7d\xea\x30\x9a\xc8\x7a\xc9\x14\xdb\x2a\x11\xc0\xdf\xbe\x2e\x08\xea\xf1\x64\x2d\x01\xa7\xa3\xf5\x48\xa8\xb6\x5e\x87\x4b\x32\x6b\x9f\x75\x88\x36\xda\xc1\xb3\x44\x21\xe0\x20\xa0\x12\x80\x25\xe9\xf8\xc6\xb4\x44\xbc\x6e\x36\xad\x35\xae\x59\x6f\x88\x97\xf3\xed\xa2\xa4\xb6\x9d\xf5\x91\x84\x5b\x37\x68\x06\xcd\x30\xd5\xce\x30\x32\x27\xdb\x6b\xb7\x2d\xf8\xd4\x5d\x72\xfb\x27\xd5\xfd\x89\x52\x28\x76\x8f\xe4\x83\x80\x9c\x07\x74\xdc\x96\xd7\x20\xf9\xa5\xc3\xbd\x9d\xad\x8f\xb6\xf3\x6c\x81\x80\x69\xf8\x72\x3f\xe3\x2b\x79\x6e\x74\xd4\x77\xc7\x7e\xea\x6b\x13\x6e\x9e\xfd\xe4\x1c\xd1\xa3\xf5\x97\xd9\xfc\xd8\x6b\xe7\x18\xaf\x16\x31\x4b\x95\xe2\xcc\x30\x95\x52\x11\xd8\xab\x14\xab\x2c\x7f\x64\xed\x11\x31\xc5\x0c\x33\x26\x66\xa9\xaa\x8e\xf9\xb2\xa4\xaa\x63\x85\x8f\x64\x99\x22\x66\x79\x51\xb2\x96\x24\x2e\xca\x7c\x6e\xe4\x5c\xff\x2d\xac\x53\xea\xd4\x52\x8b\xc2\xda\x7f\xc9\x76\x1e\x2d\x71\xc5\x60\x7d\xf7\x6f\x00\xce\xc4\x68\x02\x21\xe3\x3b\x67\xc7\x4f\x8e\x82\x89\x5b\x2c\x77\x14\xe3\xdf\x00\x00\x00\xff\xff\x34\xc0\x4c\x8a\xbd\x02\x00\x00")

func resourceDefaultZzLuaBytes() ([]byte, error) {
	return bindataRead(
		_resourceDefaultZzLua,
		"resource/default.zz.lua",
	)
}

func resourceDefaultZzLua() (*asset, error) {
	bytes, err := resourceDefaultZzLuaBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "resource/default.zz.lua", size: 701, mode: os.FileMode(436), modTime: time.Unix(1567062895, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"resource/default.zz.lua": resourceDefaultZzLua,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"resource": &bintree{nil, map[string]*bintree{
		"default.zz.lua": &bintree{resourceDefaultZzLua, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

