// Code generated by go-bindata.
// sources:
// resource/default.zz.lua
// resource/english.txt
// DO NOT EDIT!

package resource

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _resourceDefaultZzLua = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\x90\x41\x6b\xfa\x40\x10\xc5\xef\x7e\x8a\xb9\xad\x7f\x58\x65\xa3\xd1\x7f\x42\xe9\x41\x44\xf0\x56\x50\xa1\xe7\x8d\xd9\xc4\x81\xcd\x46\x36\x93\x16\x29\x7e\xf7\x32\x93\x54\xdb\x5c\xf2\xdb\x97\xcd\x9b\xf7\x86\x6c\xe1\x5d\x07\xaf\xf0\x35\x01\x00\x88\xed\xa7\x1c\x12\xa3\x61\x61\x34\x2c\x8d\x86\xd4\x68\x58\x19\x0d\x6b\xa3\xe1\xbf\xd1\x90\x19\x0d\xb9\xb9\x6b\xf9\x61\x36\x83\xe3\xfe\xed\x1d\xb6\xfb\xcd\x61\xb3\x3d\xed\x0e\x70\xdc\x9d\x5e\xe4\xd3\xf9\x62\x63\xe7\x48\xfc\x54\x4f\x55\xa6\x34\xc8\xbb\x29\x52\x46\xdb\x9d\x11\x19\xbc\x25\x0c\x09\x53\x81\xc1\xc6\x9b\x7a\x7a\x5f\x6d\x24\x24\x6c\x03\x84\xbe\x29\x5c\x14\xfd\x21\x8a\x75\xaa\x61\xad\x21\xd3\x90\xac\xd8\x3f\x94\xae\x62\x83\xfb\x64\x52\xa1\xf3\xe5\xb3\x1b\xdd\xae\x43\x53\x55\x60\x8d\x81\x78\x60\xe5\x5b\x2b\x50\xb6\x7d\xe1\x9d\x90\x3b\x63\x63\xfd\x34\x95\x15\xfc\x53\x43\x16\x7e\x14\x37\x9a\x8a\x06\xea\xc3\xc6\xc7\x71\xcc\xdb\x61\x1d\xc4\x9f\xc1\x95\x52\x37\x8c\x7c\xe7\x40\xa5\x25\xfb\x88\x33\x14\x1a\x02\x85\xde\x7b\xbe\x4e\x18\x6e\x63\xb2\xae\xb1\xde\x0b\x3f\xe7\x27\x8b\x79\x9e\xcb\xa2\x92\xb9\x31\x39\xc3\x2c\x9f\x27\xd9\xf2\xf7\xa5\x31\xff\x28\xfd\x44\xa3\x88\xa1\xfe\x3b\xcc\x3b\x22\x17\x99\x5c\xa8\x3d\x76\x17\x59\xdb\x77\x00\x00\x00\xff\xff\xa9\x92\x17\x3d\x11\x02\x00\x00")

func resourceDefaultZzLuaBytes() ([]byte, error) {
	return bindataRead(
		_resourceDefaultZzLua,
		"resource/default.zz.lua",
	)
}

func resourceDefaultZzLua() (*asset, error) {
	bytes, err := resourceDefaultZzLuaBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "resource/default.zz.lua", size: 529, mode: os.FileMode(436), modTime: time.Unix(1567780389, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _resourceEnglishTxt = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x1c\x90\xd1\x0d\xe4\x20\x0c\x44\xff\x5f\x23\xa9\x65\xcb\x70\x82\x37\xe6\x02\xf8\x04\xe4\x10\xdd\x9f\xbc\x3f\xcf\x03\x96\x47\xa3\x91\xd3\xdf\x89\x94\x82\xb4\x84\x74\x45\x06\x32\x11\x4e\xb9\x1e\x4e\xbd\xe4\x1d\xca\xa9\xda\x38\x95\xf3\x9d\x5c\xd2\x8e\x1f\xb9\xbc\x2a\x97\xbf\x25\x91\x72\x8a\xdf\x94\x13\xc9\x7f\xca\xf9\x7a\xe7\xdb\xbd\x72\xeb\xe4\xf6\xdc\x6e\x6e\xf7\xc4\xed\xf1\xc4\x24\x61\xf2\x4f\x31\x3d\x06\xa6\x3d\x54\xc7\x74\x63\x8a\xe5\x8a\xe5\x81\xf9\xe2\x73\x94\xc2\xe7\xa8\xe4\x2f\xb9\x91\x07\x79\x1e\x01\x3e\xfc\x79\xc7\xe4\x69\xbe\x28\xf9\x51\x8a\xfb\x43\x55\x69\x54\xa5\x6e\x9a\x4f\x62\xd9\x1c\xff\xe2\x86\x3f\xb2\xf1\x07\x6f\x8a\x37\xbc\x13\x05\x74\x95\x52\x36\x3d\xdf\x36\x19\xb2\x19\xaa\x0c\x53\x86\x57\x9d\x16\xd1\x43\x31\x9c\xa9\xa5\x30\x4d\x22\x41\x0c\xa6\x69\x0b\x74\x0d\xee\x00\x71\xf2\x04\x07\x33\x57\x65\x3a\xef\x5f\x96\xb4\xc9\x92\xc1\x0a\x8f\x15\x17\x4b\x59\x61\xb2\xc2\x64\x99\xb3\x6c\xb3\x72\xac\xf3\x34\xd6\xaf\xdc\xad\x62\x6c\x1d\x6c\x7f\x8f\xae\x31\x7a\xe0\x7f\x00\x00\x00\xff\xff\xd6\xa3\xa5\xd2\xbd\x01\x00\x00")

func resourceEnglishTxtBytes() ([]byte, error) {
	return bindataRead(
		_resourceEnglishTxt,
		"resource/english.txt",
	)
}

func resourceEnglishTxt() (*asset, error) {
	bytes, err := resourceEnglishTxtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "resource/english.txt", size: 445, mode: os.FileMode(436), modTime: time.Unix(1567566056, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"resource/default.zz.lua": resourceDefaultZzLua,
	"resource/english.txt": resourceEnglishTxt,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"resource": &bintree{nil, map[string]*bintree{
		"default.zz.lua": &bintree{resourceDefaultZzLua, map[string]*bintree{}},
		"english.txt": &bintree{resourceEnglishTxt, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

