package main

import (
	"fmt"
	"github.com/dqinyuan/go-randgen/gendata"
	"github.com/dqinyuan/go-randgen/grammar"
	"github.com/dqinyuan/go-randgen/resource"
	"github.com/spf13/cobra"
	"io/ioutil"
	"log"
	"math"
	"os"
)


var zzPath string
var yyPath string

var queries int
var maxRecursive int
var root string

var debug bool

var rootCmd = &cobra.Command{
	Use:   "go-randgen",
	Short: "QA tool for fuzzy test just like mysql go-randgen",
}

// init command flag
func initCmd() {
	rootCmd.PersistentFlags().StringVarP(&zzPath, "zz", "Z",
		"", "zz file path, go go-randgen have a default zz")
	rootCmd.PersistentFlags().StringVarP(&yyPath, "yy", "Y","", "yy file path, required")
	rootCmd.PersistentFlags().IntVarP(&queries, "queries", "Q", 100, "random sql num generated by zz")
	rootCmd.PersistentFlags().StringVarP(&root, "root", "R", "query", "root bnf expression to generate sqls")

	rootCmd.PersistentFlags().IntVar(&maxRecursive, "maxrecur", 5,
		"yy expression most recursive number, if you want recursive without limit ,set it <= 0")
	rootCmd.PersistentFlags().BoolVar(&debug, "debug", false,
		"print detail generate path")

	rootCmd.AddCommand(newExecCmd())
	rootCmd.AddCommand(newGentestCmd())
	rootCmd.AddCommand(newGenDataCmd())
}

func main() {
	initCmd()
	if err := rootCmd.Execute(); err != nil {
		fmt.Println(rootCmd.UsageString())
		os.Exit(1)
	}
}

func getDdls() ([]string, gendata.Keyfun) {
	var zzBs []byte
	var err error
	if zzPath == "" {
		log.Println("load default zz")
		zzBs, err = resource.Asset("resource/default.zz.lua")
	} else {
		zzBs, err = ioutil.ReadFile(zzPath)
	}

	if err != nil {
		log.Fatalf("load zz fail, %v\n", err)
	}

	zz := string(zzBs)

	ddls, keyf, err := gendata.ByZz(zz)
	if err != nil {
		log.Fatalln(err)
	}

	return ddls, keyf
}

func getRandSqls(keyf gendata.Keyfun) []string {
	yyBs, err := ioutil.ReadFile(yyPath)
	if err != nil {
		log.Fatalf("Fatal Error: load yy from %s fail, %v\n", yyPath, err)
	}

	yy := string(yyBs)

	if maxRecursive <= 0 {
		maxRecursive = math.MaxInt32
	}

	randomSqls, err := grammar.ByYy(yy, queries, root, maxRecursive, keyf, debug)
	if err != nil {
		log.Fatalln("Fatal Error: " + err.Error())
	}

	return randomSqls
}